[package]
name = "lingest"
version = "1.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi8"] }
napi-derive = "2"
glob = "0.3"
walkdir = "2"
rayon = "1.7"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true 