/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LingestOptions {
  cwd: string
  outputPath: string
  ignoreGlobs: Array<string>
  includeGlobs: Array<string>
  noTree: boolean
  dryRun: boolean
}
export interface LingestResult {
  tree?: string
  fileContents: Array<FileContent>
  processedCount: number
}
export interface FileContent {
  path: string
  content: string
  error?: string
}
export declare function processDirectory(options: LingestOptions): LingestResult
